### PR TITLE
fill in consumer_details for DetailedQueueInfo

### PR DESCRIPTION
**Pull request by jiancheung**
This allows `DetailedQueueInfo` to unmarshal more data from the `GET /api/queues/{vhost}/{name}` endpoint.
One caveat now though is that the endpoint is more likely to return an error unmarshaling if `ConsumerDetail.ChannelDetails` is full of `"unknown"` string values.

### CODE REVIEW

**Comment by nathanleiby** [comment]
I don't understand the caveat. Why would data fail to unmarshal sometimes? Is there more than one possible JSON schema?

Is the `ChannelDetails` field in particular necessary and might you omit it if it can cause problems?

**Comment by jiancheung** [comment]
@nathanleiby the goal of this PR is to get `ConsumerDetail` and `ChannelDetails` into the `DetailedQueueInfo` struct.
`ChannelDetails` is usually well defined with a predictable struct with good types, but sometimes we get situations where the API returns
```
            "channel_details": {
                "connection_name": "unknown",
                "name": "unknown",
                "number": "unknown",
                "peer_host": "unknown",
                "peer_port": "unknown",
                "user": "unknown"
            },
```
and so it fails to unmarshall all of these `"unknown"` into `bool/int`

**Comment by nathanleiby** [comment]
I'd be curious what the upstream maintainers think here and if they intentionally avoided this.

I can't think of an easy workaround given Go's type strictness, other than to make these interfaces and handle them with a type switch later.

--

One concern is that we often do see Unknown consumers as a symptom of poorly performing queues. I'd want to ensure that whatever tools/alerts we build will still work in this condition.

**Comment by nathanleiby** [comment]
@jiancheung assigned back to you - feel free to re-assign if you'd like another review later!

**Comment by burnsed** [comment]
included in https://github.com/Clever/rabbit-hole/pull/5

**Pull request closed without merging**
